# Generated by Django 6.0.1 on 2026-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvite',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
